#kind: Role
#apiVersion: rbac.authorization.k8s.io/v1beta1
#metadata:
#  name: tiller-manager
#  namespace: x
#rules:
#- apiGroups: ["apps"]
#  resources: ["pods"]
#  verbs: ["get"]
#---
#
# Bind service account 'admin' in namespace 'default' to the 'developer' role
#   Note: This is an example of restricting access
#         and does not imply a comprehensive solution.
#         The 'developer' role is assumed to exist in these examples.
#
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rb-admin-dev
  namespace: default
subjects:
- kind: ServiceAccount
  name: admin
  namespace: default
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io

